url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "vesheff's blog" # the name of your site, e.g. ACME Corp.

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

sass:
  style: compressed

theme: jekyll-theme-hacker